# Generated by Django 5.2.4 on 2025-08-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aulaagendada',
            name='hora',
        ),
        migrations.AddField(
            model_name='aulaagendada',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
