# Generated by Django 5.2.4 on 2025-08-03 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_remove_aulaagendada_hora_aulaagendada_confirmada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aulaagendada',
            options={'ordering': ['data'], 'verbose_name': 'Aula Agendada', 'verbose_name_plural': 'Aulas Agendadas'},
        ),
        migrations.AlterField(
            model_name='aulaagendada',
            name='aluno',
            field=models.ForeignKey(limit_choices_to={'tipo': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='aulas_agendadas_aluno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aulaagendada',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aulaagendada',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'tipo': 'PROFESSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='aulas_agendadas_professor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aulaagendada',
            name='tipo',
            field=models.CharField(choices=[('CANTO', 'Canto'), ('TECLADO', 'Teclado'), ('ORGAO', 'Órgão')], max_length=10),
        ),
    ]
