# Generated by Django 5.2.4 on 2025-08-05 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aulas', '0003_delete_aulaagendada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('mundo', models.CharField(choices=[('1', 'Mundo 1'), ('2', 'Mundo 2'), ('3', 'Mundo 3')], max_length=1)),
                ('ordem', models.IntegerField(default=0)),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aulas.aula')),
            ],
        ),
        migrations.CreateModel(
            name='MissaoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missoes.missao')),
            ],
        ),
    ]
