# Generated by Django 5.2.4 on 2025-08-03 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_aulaagendada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AulaAgendada',
        ),
    ]
